services:
  howmuch:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV:-production}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "3000:80"
    restart: unless-stopped
    container_name: howmuch-currency-converter
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    environment:
      - EXCHANGE_RATES_API_KEY=${EXCHANGE_RATES_API_KEY}
      - EXCHANGE_RATES_API_URL=${EXCHANGE_RATES_API_URL}
      - PORT=3001
    ports:
      - "3001:3001"
    restart: unless-stopped
    container_name: howmuch-backend
    env_file:
      - .env